# Use the official Node.js image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install React.js dependencies
RUN npm install

# Copy the React app source code
COPY . .

# Expose port 3000 for the React development server
EXPOSE 3000

# Start the React app in development mode
CMD ["npm", "start"]
