services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    image: php82-python:latest
    container_name: php82-python
    ports:
      - "8585:80"      # Apache
      - "5000:5000"    # Email service
      - "5001:5001"    # FTP uploader
      - "5002:5002"    # WAHA sender
    volumes:
      - /home/puneet/www/:/var/www/html
      - /home/puneet/config:/var/www/config
      - /home/puneet/logs:/var/log/app

    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped
