version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php82_mysqli_ftp_mail
    ports:
      - "8585:80"
    volumes:
      - /home/puneet/www/:/var/www/html
