services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: apache-php
    volumes:
      - type: bind
        source: /home/puneet/www
        target: /var/www/html
    ports:
      - "9090:80"
    networks:
      - app-network

  react-app1:
    build:
      context: /home/puneet/react/app1
      dockerfile: /home/puneet/www/stacks/Dockerfile-react
    container_name: react-app1
    ports:
      - "3001:3000"
    networks:
      - app-network

  react-app2:
    build:
      context: /home/puneet/react/app2
      dockerfile: /home/puneet/www/stacks/Dockerfile-react
    container_name: react-app2
    ports:
      - "3002:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
